### PR TITLE
atomicwrites: move to ::python, pytest needs it

### PR DESCRIPTION
**Pull request by Cogitri**
Do you still want to be in BUGS_TO though?

### CODE REVIEW

**Comment by flocke** [comment]
I moved off Exherbo a while back so I think it's best to leave me out of BUGS_TO. Is this already merged to ::python, if yes I will merge it here as well.

**Comment by Cogitri** [comment]
No, I'll merge the MR in ::python tomorrow and ping you here :)

**Comment by flocke** [comment]
Sounds good :+1:

**Comment by Cogitri** [comment]
Alright, it's merged now: https://git.exherbo.org/python.git/diff/?id2=537f283&id=a10040f

**Comment by Cogitri** [comment]
Thanks :)

**Pull request merged**
